version: '3.4'

services:
  backend:
    image: gocampo/backend
    restart: always
    ports: 
      - 8100:80
    environment:
      - ASPNETCORE_URLS=http://+
      - PredictionAPI__Key=${PredictionAPI__Key}
      - DBSettings__ConnectionString=${DBSettings__ConnectionString:-mongodb://mongodb:27017}
      - DBSettings__Database=${DBSettings__Database:-moneditas}
      - DBSettings__Collection=${DBSettings__Collection:-Results}

  mongodb:
    image: mongo
    expose: 
      - 27017
    volumes:
      - data:/data/db
    restart: always

volumes:
  data:
