name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: CD backend
      run: cd backend
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: cd backend && docker build . --file Dockerfile --tag gocampo/backend:latest 

    - name: Push Docker image
      run: docker push gocampo/backend:latest
      
    - name: scp-pipeline
      uses: cross-the-world/scp-pipeline@v1.2.1
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.HOST_USER }}
        pass: ${{ secrets.HOST_PASSWORD }}
        local: .//docker-compose.yaml
        remote: /opt/moneditas
    
